version: '3.0'
services:
  PHP_app:
    build: .
    container_name: guest_book
    image: madridistka98/guest_book
    tty: true
    environment: 
      - APACHE_LOG_DIR=/var/www/html
    ports:
      - "80:80"
    links:
      - db
    volumes:  
    - ./app:/var/www/html
      
  db:
    image: mysql:8.0.21
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
    command: 
      - "--innodb_use_native_aio=0"
      - "--innodb_buffer_pool_size=10M"
      - "--innodb_log_file_size=100M"
      - "--secure-file-priv=NULL"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8580:80"
    links:
      - db  