<form novalidate>
    <div class="row">
        <h3 class="text-center mx-auto my-4">Skontaktuj się</h3>
    </div>
    <div class="row">
        <div class="form-group col">
            <label for="contact-form__email">Email</label>
            <input required name="email" type="email" class="form-control" id="contact-form__email" aria-describedby="emailHelp">
            <div class="invalid-feedback">
              Podaj poprawny adres email
            </div>
          </div>
  </div>
  <div class="form-group">
    <label for="contact-form__text">Wiadomość</label>
    <textarea name="message" class="form-control" id="contact-form__text" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-primary btn-block text-center mx-auto w-25">Dodaj</button>
</form>