
                <div class="card">
                    <div class="card-header" id="heading-<?= $guest['ID'] ?>">
                        <div class="d-flex flex-sm-row flex-column">
                        <p class="name lead"><?= $guest["Nickname"] ?></p>
                        <p class="email lead ml-sm-4"><?= $guest["Email"] ?></p>
                            <button class="btn btn-link ml-sm-auto mr-sm-0 mx-auto text-sm-right text-center collapsed" type="button" data-toggle="collapse" data-target="#collapse-<?= $guest['ID'] ?>" aria-expanded="false" aria-controls="collapse-<?= $guest['ID'] ?>">
                                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-down-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>
                                </svg>
                            </button>
                            <?php if(isset($this->adminName)): ?>
                                <form action="/delete.php" method="POST">
                                <input type="hidden" name="guest-id" value="<?= $guest['ID'] ?>" />
                                <button data-delete="<?= $guest['ID'] ?>" class="btn btn-link text-danger text-sm-right text-center ml-2" type="submit">
                                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                                </button>
                                </form>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div id="collapse-<?= $guest['ID'] ?>" class="collapse" aria-labelledby="heading-<?= $guest['ID'] ?>" data-parent="#accordionExample">
                    <div class="card-body">
                    <?= $guest["Text"] ?>
                    </div>
                    </div>
                </div>
            