<form action="/add.php" method="POST" novalidate>
    <div class="row">
        <div class="form-group col">
            <label for="guest-card__email">Email</label>
            <input required name="email" type="email" class="form-control" id="guest-card__email" aria-describedby="emailHelp">
            <div class="invalid-feedback">
              Podaj poprawny adres email
            </div>
          </div>
        <div class="form-group col">
            <label for="guest-card__nickname">Nazwa</label>
            <input required name="nickname" type="text" class="form-control" id="guest-card__nickname">
            <div class="invalid-feedback">
              Podaj poprawny nick
            </div>
          </div>
  </div>
  <div class="form-group">
    <label for="guest-card__text">Tekst</label>
    <textarea name="message" class="form-control" id="guest-card__text" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-primary btn-block text-center mx-auto w-25">Dodaj</button>
</form>