<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container">
                <a class="navbar-brand" href="/">Guest Book</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="wascollapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto w-100">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/kontakt.php">Kontakt</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/informacje.php">Informacje</a>
                    </li>
                    

                    <?php if(isset($this->adminName)): ?>
                            <li class="nav-item ml-auto">
                                <h4>Witaj <?= $this->adminName ?></h4>
                            </li>
                        </ul>
                    <?php else: ?> 
                        </ul>
                        <form action="/index.php" method="POST" class="form-inline">
                        <input class="form-control mr-sm-2" type="input" name="admin[login]" placeholder="Login" aria-label="login">
                        <input class="form-control mr-sm-2" type="password" name="admin[password]" placeholder="Hasło" aria-label="password">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Zaloguj się</button>
                        </form>
                    <?php endif; ?>
                </div>  
                </div>
            </nav>